name: Run CI checks

on: [pull_request]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing affected apps
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected:lint --base=origin/master
      # - run: npm run nx affected:test
      # - run: npm run nx affected:e2e
